### ISSUE TITLE
Upgrade to 3.3.0

### ISSUE THREAD

**Issue by Abdalrhmanalfalaha** [mattieserver/netbox-topology-views#148]
Hello, i want to update the plugin now, I do it like this:

`$ pip install netbox-topology-views –upgrade`
**Requirement already satisfied: netbox-topology-views in /opt/netbox-3.3.0/venv/lib/python3.8/site-packages (2.0.2)**

`$ python3 manage.py collectstatic --no-input`
**python3: can't open file 'manage.py': [Errno 2] No such file or directory**

can i know what the problem is? It also doesn't matter if I do it with the virtual environment!

Thanks!

**Comment by mattieserver** [comment]
Hi,

Are you in the netbox folder?
You might need to "cd" to the correct subfolder.
I believe/opt/netbox/netbox/ might be the correct path if you followed the steps from netbox wiki.
(Manage.py needs to exist in the folder where you run the python3 command)
________________________________
From: Abdalrhman ***@***.***>
Sent: Friday, September 2, 2022 9:31:18 AM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Upgrade to 3.3.0 (Issue #148)


Hello, i want to update the plugin now, I do it like this:

$ pip install netbox-topology-views –upgrade
Requirement already satisfied: netbox-topology-views in /opt/netbox-3.3.0/venv/lib/python3.8/site-packages (2.0.2)

$ python3 manage.py collectstatic --no-input
python3: can't open file 'manage.py': [Errno 2] No such file or directory

can i know what the problem is? It also doesn't matter if I do it with the virtual environment!

Thanks!

**Comment by mikesrus** [comment]
@Abdalrhmanalfalaha use `pip install netbox-topology-views --upgrade --pre` to upgrade

**Comment by Abdalrhmanalfalaha** [comment]
@mikesrus @mattieserver Thanks! this worked with `--pre` but not yet with python3, I also ran it in the folder like this:

`$ which python3`
**/usr/bin/python3**

`$ cd /usr/bin/`
`$ python3 manage.py collectstatic --no-input`
**python3: can't open file 'manage.py': [Errno 2] No such file or directory**

**Comment by mattieserver** [comment]
Can you try with:
`cd /opt/netbox/netbox`
`python3 manage.py collectstatic --no-input`

**Comment by Abdalrhmanalfalaha** [comment]
@mattieserver It brings the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox-3.3.0/netbox/netbox/settings.py", line 652, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nextbox_ui_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/dist-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.3.0/netbox/netbox/settings.py", line 655, in <module>
    raise ImproperlyConfigured(

django.core.exceptions.ImproperlyConfigured: Unable to import plugin nextbox_ui_plugin: Module not found. Check that the plugin module has been installed within the correct Python environment.

**Comment by Abdalrhmanalfalaha** [comment]
But the plugin _nextbox-ui-plugin_ is also installed:
`$ source /opt/netbox/venv/bin/activate`
`$ pip3 install nextbox-ui-plugin`
**Requirement already satisfied: nextbox-ui-plugin in /opt/netbox-3.3.0/venv/lib/python3.8/site-packages (0.9.2)**

**Comment by ThomasADavis** [comment]
I kinda sort cheat..  add this to your requirements.txt or equivalent.

```
git+https://github.com/mattieserver/netbox-topology-views/@v3.0.0-beta.2
```

**Comment by mattieserver** [comment]
Can you try with:

First run `source /opt/netbox/venv/bin/activate` to enter the Python virtual environment.


Then run 
```bash
cd /opt/netbox/netbox
pip3 install netbox-topology-views
python3 manage.py collectstatic --no-input
```

**Comment by Abdalrhmanalfalaha** [comment]
Thanks!
