### ISSUE TITLE
Lost support for python 3.8 (AttributeError: 'str' object has no attribute 'removeprefix')

### ISSUE THREAD

**Issue by candlerb** [mattieserver/netbox-topology-views#216]
### NetBox version

v3.3.10 under Ubuntu 20.04 (Python 3.8)

### Topology Views version

v3.1.0 (latest pip package)

### Steps to Reproduce

1. Existing installation of Netbox v3.3.9 with NTV
2. Attempt to upgrade to Netbox v3.3.10

My `local_requirements.txt` contains

```
...
netbox-topology-views
```

(version not pinned)

### Expected Behavior

Successful upgrade

### Observed Behavior

```
...
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/models.py", line 15, in <module>
    from netbox_topology_views.utils import (
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_topology_views/utils.py", line 12, in <module>
    CONF_IMAGE_DIR: Path = Path(settings.STATIC_ROOT) / settings.PLUGINS_CONFIG[
AttributeError: 'str' object has no attribute 'removeprefix'
```

It seems that str.removeprefix was [added in Python 3.9](https://docs.python.org/3/whatsnew/3.9.html#new-string-methods-to-remove-prefixes-and-suffixes).  However, for now at least, Netbox still supports 3.8 as [minimum Python version](https://docs.netbox.dev/en/stable/installation/#requirements) (in fact only 3.8-3.10; support for 3.11 is in the Netbox v3.4 beta)

**Comment by iStatiK** [comment]
Hi @candlerb ,
Were you able to get your NB instance back up?  I have failed to do so even by downgrading NB.

**Comment by candlerb** [comment]
> Hi @candlerb , Were you able to get your NB instance back up? I have failed to do so even by downgrading NB.

I got it back up by disabling the netbox-topology-views plugin entirely.

It would probably also have been possible to do this by pinning NTB to a previous version. Looking at git history I think `netbox-topology-views==3.0.1` would work (i.e. avoid 3.1.0), but I've not tested this.

The only other option would be to upgrade python to 3.9+

**Comment by iStatiK** [comment]
> > Hi @candlerb , Were you able to get your NB instance back up? I have failed to do so even by downgrading NB.
> 
> I got it back up by disabling the netbox-topology-views plugin entirely.
> 
> It would probably also have been possible to do this by pinning NTB to a previous version. Looking at git history I think `netbox-topology-views==3.0.1` would work (i.e. avoid 3.1.0), but I've not tested this.
> 
> The only other option would be to upgrade python to 3.9+

Interesting.  

I commented out in local_requirements, removed from configuration.py, and uninstalled in env using `pip3 uninstall netbox-topology-views`

Going to re-enable the older version and see if it works.  Then if all else fails, upgrade to 3.9 and see what breaks.

**Comment by candlerb** [comment]
> I commented out in local_requirements, removed from configuration.py, and uninstalled in env using `pip3 uninstall netbox-topology-views`

`pip3 uninstall` wouldn't be needed.  As long as it's gone from local_requirements.txt and configuration.py, then `upgrade.sh` will build a fresh virtualenv without it.

**Comment by iStatiK** [comment]
> > I commented out in local_requirements, removed from configuration.py, and uninstalled in env using `pip3 uninstall netbox-topology-views`
> 
> `pip3 uninstall` wouldn't be needed. As long as it's gone from local_requirements.txt and configuration.py, then `upgrade.sh` will build a fresh virtualenv without it.

Agreed, but thought i would do it just to make sure.
I was able to upgrade NB to 3.4.  Just had to install python3.9 & libpython3.9-dev, then run upgrade by pass 3.9: `sudo PYTHON=/usr/bin/python3.9 ./upgrade.sh`

Still using 3.0.1 of NTV, however.

**Comment by mattieserver** [comment]
This will be fixed in the next release.
