### ISSUE TITLE
Import error: undefined "urlpattern" attribute/class

### ISSUE THREAD

**Issue by cj0duke** [mattieserver/netbox-topology-views#369]
### NetBox version

v3.6.0

### Topology Views version

v3.6.2

### Steps to Reproduce

Upgrade:
1. upgrade from netbox 3.5.7 to 3.6.0 with local_requirements & configuration.py in place
2. ./upgrade.sh

Installation:
1. fresh netbox 3.6.0 install
2. install netbox-topo
3. python migrate

### Expected Behavior

upgrade/install to latest version

### Observed Behavior

following error occurs either by installation or upgrade:
```
Traceback (most recent call last):
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/urls.py", line 4, in <module>
    from . import models, views
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/views.py", line 42, in <module>
    from netbox_topology_views.filters import DeviceFilterSet, CoordinatesFilterSet
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/filters.py", line 10, in <module>
    class DeviceFilterSet(TenancyFilterSet, NetBoxModelFilterSet):
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django_filters/filterset.py", line 62, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/opt/netbox-3.6.0/netbox/netbox/filtersets.py", line 222, in get_filters
    additional_filters.update(cls.get_additional_lookups(existing_filter_name, existing_filter))
  File "/opt/netbox-3.6.0/netbox/netbox/filtersets.py", line 179, in get_additional_lookups
    resolve_field(field, lookup_expr)  # Will raise FieldLookupError if the lookup is invalid
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django_filters/utils.py", line 204, in resolve_field
    query = model_field.model._default_manager.all().query
AttributeError: 'NoneType' object has no attribute 'model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox-3.6.0/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.6.0/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.6.0/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "netbox_topology_views.urls" does not define a "urlpatterns" attribute/class

```

**Comment by mattieserver** [comment]
Yes, this is expected as there are some breaking changes in v3.6.0. Please remove the plugin until we release a new version.
________________________________
From: cj0duke ***@***.***>
Sent: Thursday, August 31, 2023 12:18:41 AM
To: mattieserver/netbox-topology-views ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattieserver/netbox-topology-views] Import error: undefined "urlpattern" attribute/class (Issue #369)


NetBox version

v3.6.0

Topology Views version

v3.6.2

Steps to Reproduce

Upgrade:

  1.  upgrade from netbox 3.5.7 to 3.6.0 with local_requirements & configuration.py in place
  2.  ./upgrade.sh

Installation:

  1.  fresh netbox 3.6.0 install
  2.  install netbox-topo
  3.  python migrate

Expected Behavior

upgrade/install to latest version

Observed Behavior

following error occurs either by installation or upgrade:

Traceback (most recent call last):
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/urls.py", line 4, in <module>
    from . import models, views
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/views.py", line 42, in <module>
    from netbox_topology_views.filters import DeviceFilterSet, CoordinatesFilterSet
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/netbox_topology_views/filters.py", line 10, in <module>
    class DeviceFilterSet(TenancyFilterSet, NetBoxModelFilterSet):
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django_filters/filterset.py", line 62, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/opt/netbox-3.6.0/netbox/netbox/filtersets.py", line 222, in get_filters
    additional_filters.update(cls.get_additional_lookups(existing_filter_name, existing_filter))
  File "/opt/netbox-3.6.0/netbox/netbox/filtersets.py", line 179, in get_additional_lookups
    resolve_field(field, lookup_expr)  # Will raise FieldLookupError if the lookup is invalid
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django_filters/utils.py", line 204, in resolve_field
    query = model_field.model._default_manager.all().query
AttributeError: 'NoneType' object has no attribute 'model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox-3.6.0/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-3.6.0/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.6.0/netbox/extras/plugins/urls.py", line 31, in <module>
    urlpatterns = import_string(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox-3.6.0/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "netbox_topology_views.urls" does not define a "urlpatterns" attribute/class

**Comment by mattieserver** [comment]
This is fixed with https://github.com/mattieserver/netbox-topology-views/releases/tag/3.7.0
