### ISSUE TITLE
Crashing on netbox 3.7.0

### ISSUE THREAD

**Issue by sliddjur** [mattieserver/netbox-topology-views#444]
### NetBox version

v3.7.0

### Topology Views version

v3.8.1

### Steps to Reproduce

Enable topology views in `local_requirements.txt`
Enable topology view in `configuration.py`

### Expected Behavior

I expect it to work.

### Observed Behavior

From `netbox-rq` logs.

```
Jan 08 10:02:14 no-bgo-netbox systemd[1]: Started NetBox Request Queue Worker.
Jan 08 10:02:15 no-bgo-netbox python3[63673]: Traceback (most recent call last):
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/netbox/manage.py", line 10, in <module>
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     execute_from_command_line(sys.argv)
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     utility.execute()
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     django.setup()
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     apps.populate(settings.INSTALLED_APPS)
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     app_config.import_models()
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     self.models_module = import_module(models_module_name)
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Jan 08 10:02:15 no-bgo-netbox python3[63673]:   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_topology_views/models.py", line 13, in <module>
Jan 08 10:02:15 no-bgo-netbox python3[63673]:     from netbox.models.features import (
Jan 08 10:02:15 no-bgo-netbox python3[63673]: ImportError: cannot import name 'WebhooksMixin' from 'netbox.models.features' (/opt/netbox/netbox/netbox/models/features.py)
```

**Comment by mattieserver** [comment]
please use netbox-topology-views==3.9b1.
