### ISSUE TITLE
Install error: ImportError: cannot import name 'PluginConfig' from 'extras.plugins' (unknown location)

### ISSUE THREAD

**Issue by vishnubraj** [mattieserver/netbox-topology-views#503]
### NetBox version

v4.0.2

### Topology Views version

3.9.1

### Steps to Reproduce

I tried installing the plugin for the netbox 4.0.2 version and I am getting the below error.

```
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 426, in run_from_argv
    connections.close_all()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/connection.py", line 76, in all
    return [
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 743, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_topology_views/__init__.py", line 1, in <module>
    from extras.plugins import PluginConfig
ImportError: cannot import name 'PluginConfig' from 'extras.plugins' (unknown location)
```

### Expected Behavior

Installation should be successfull. 

### Observed Behavior

Installation failed

**Comment by cruse1977** [comment]
This plugin is not yet compatible with NetBox 4.0; hence the error

**Comment by mattieserver** [comment]
You can try the v4.0.0-beta.1 release for netbox V4 support.

**Comment by vishnubraj** [comment]
Thank you for your help, @mattieserver. I tested the plugin with the v4.0.0-beta.1 release, and it works. I have a question. I have all the tor switches connected to my core switch. In the topology view, it displays the switches as a star. If I try to move a switch, it just comes back to the same position, and nothing gets updated in the Coordinate Groups. Is this expected behavior for a star topology, or is it a bug? I've never used the netbox-topology-views plugin before, so I'm not sure.

**Comment by dreng** [comment]
1. You need to set allow_coordinates_saving in the config file. See https://github.com/netbox-community/netbox-topology-views?tab=readme-ov-file#individual-options
2. You need to check Save Coordinates in the Filters pane.

**Comment by vishnubraj** [comment]
@dreng I tried that still not working(coordinate groups are not saved). I updated to the latest beta `v4.0.0-beta.2` Even this one also not working.

**Comment by mattieserver** [comment]
Please provide more information

**Comment by vishnubraj** [comment]
@mattieserver  Its providing the topology view but the coordinates are not saved. When I move the device it comes back to the same position.

**Comment by mattieserver** [comment]
Can you see if the browser console logs any errors after you drag a device to a new position?

**Comment by vishnubraj** [comment]
No requests are going out when I drag a device to a new position.  No errors on the console.

**Comment by mattieserver** [comment]
Please clear the browser cache and try again. I just verified locally that it worked with the beta 2 release.
