### ISSUE TITLE
Failing to install on 4.0

### ISSUE THREAD

**Issue by deanfourie1** [mattieserver/netbox-topology-views#529]
### NetBox version

v4.0.7

### Topology Views version

v4.0.0

### Steps to Reproduce

cd /opt/netbox
Active venv >> source /opt/netbox/venv/bin/activate
install with >> pip install netbox-topology-views
add to local_requirements.txt >> cd /opt/netbox >> echo netbox-topology-views >> local_requirements.txt
add to configuration.py >> cd /opt/netbox/netbox/netbox >> nano configuration.py >> add "netbox_topology_views",
cd /opt/netbox/netbox
pip3 install netbox-topology-views
python3 manage.py migrate netbox_topology_views
python3 manage.py collectstatic --no-input

Added the following to configuration.py

```
PLUGINS_CONFIG = {
    'netbox_topology_views': {
        'static_image_directory': 'netbox_topology_views/img',
        'allow_coordinates_saving': True,
        'always_save_coordinates': True
    }
}
```

cd /opt/netbox
./upgrade.sh

### Expected Behavior

For ./upgrad.sh to complete, reboot netbox and netbox-rq and be able to use netbox-typology.

### Observed Behavior

```
venv) root@netbox-local:/opt/netbox/netbox# python3 manage.py migrate netbox_topology_views
/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
Operations to perform:
  Apply all migrations: netbox_topology_views
Running migrations:
  No migrations to apply.
(venv) root@netbox-local:/opt/netbox/netbox# 
```

```
venv) root@netbox-local:/opt/netbox/netbox# python3 manage.py collectstatic --no-input
/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)

0 static files copied to '/opt/netbox/netbox/static', 544 unmodified.
(venv) root@netbox-local:/opt/netbox/netbox# 
```

```
  netbox_topology_views.coordinategroup... Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/server_cursor.py", line 294, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "netbox_topology_views_coordinategroup" does not exist
LINE 1: ...opology_views_coordinategroup"."description" FROM "netbox_to...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/extras/management/commands/reindex.py", line 95, in handle
    i = search_backend.cache(model.objects.iterator(), remove_existing=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/netbox/search/backends.py", line 197, in cache
    for instance in instances:
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 518, in _iterator
    yield from iterable
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/server_cursor.py", line 294, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "netbox_topology_views_coordinategroup" does not exist
LINE 1: ...opology_views_coordinategroup"."description" FROM "netbox_to...
                                                             ^
root@netbox-local:/opt/netbox# 
```

**Comment by mattieserver** [comment]
So you ran the command ./upgrade.sh? 
And that worked, or does ./upgrade.sh also cause issues?

**Comment by deanfourie1** [comment]
If I dont have the plugin configured in local_requirements and configuration.py, the ./upgrade.sh completes without issues,

When I add the plugin back into my local_requirements and confguration.py, then the ./upgrade.sh fails with the above.

**Comment by deanfourie1** [comment]
Anyone>

**Comment by deanfourie1** [comment]
Any idea why I cannot install this plugin?

**Comment by deanfourie1** [comment]
Is there a way to recreate the tables?

**Comment by dreng** [comment]
> Is there a way to recreate the tables?

While you're talking about "recreating" tables, I don't see a proof that any tables have been created at all. Your log says:

> Operations to perform:
>   Apply all migrations: netbox_topology_views
> Running migrations:
>   No migrations to apply.

That can't be the whole truth. You can show all applied migrations in your venv with

`python3 /opt/netbox/netbox/manage.py showmigrations`

Have any migrations for netbox_topology_views been applied before?

In addition you can have a look at dbshell and check the tables:

1. Start dbshell
`python3 /opt/netbox/netbox/manage.py dbshell`
2. List tables
`\dt`
3. You may want to filter the list by tables starting with an "n"
`\dt n*`

It is possible to revert migrations (if you'd like to re-apply them), but to be honest, I've never done that. So be careful if you do that. Make a backup or snapshot first. This is what I have found: https://stackoverflow.com/questions/32123477/how-to-revert-the-last-migration

I'm converting this thread into a discussion, as it doesn't seem to be bug but an individual problem.
