### ISSUE TITLE
Permission/File error during install

### ISSUE THREAD

**Issue by russellstrei** [mattieserver/netbox-topology-views#586]
### NetBox version

NetBox Community v4.1.7 (2024-11-21)

### Topology Views version

Latest I presume

### Steps to Reproduce

Running the latest version of netbox.  When I execute the steps in the install guide I get the following error:

python3 /opt/netbox/netbox/manage.py migrate netbox_topology_views
python3 /opt/netbox/netbox/manage.py collectstatic --no-input

```
(venv) ubuntu@netbox:/opt/netbox/netbox/static$ python3 /opt/netbox/netbox/manage.py migrate netbox_topology_views
Operations to perform:
  Apply all migrations: netbox_topology_views
Running migrations:
  No migrations to apply.
(venv) ubuntu@netbox:/opt/netbox/netbox/static$ python3 /opt/netbox/netbox/manage.py collectstatic --no-input
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
    handler(path, prefixed_path, storage)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 378, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/files/storage/base.py", line 49, in save
    name = self._save(name, content)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 87, in _save
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/netbox/netbox/static/netbox_topology_views'
```

Upon browsing the directory, there is no file or folder called netbox_topology_views in the static directory.

Ubuntu 22.04.5 LTS

### Expected Behavior

I think it'd install properly and not die

### Observed Behavior

It died saying Permission denied.  I used the same steps for another plugin (inventory) which worked.

**Comment by russellstrei** [comment]
![netbox-topology-views-error](https://github.com/user-attachments/assets/f2ab4fe1-da84-4f5d-8d35-636383acf14d)

**Comment by russellstrei** [comment]
These are the steps that I followed from ADMIN>System>Plugins>NetBox Topology Views
Example URL: https://netbox/core/plugins/netbox_topology_views/

![netbox-topology-views-steps-followed](https://github.com/user-attachments/assets/424c84ad-3bfd-484e-b370-49818d2fd5dd)

**Comment by cruse1977** [comment]
hi @russellstrei  - admin->plugins install guide pulls from the readme in github. 

Dependent on how you installed netbox - you may need sudo in front of all of those - the OSError tells you this, or sudo su before you run the commands.

**Comment by dreng** [comment]
I just want to add the following: First, become a superuser with "sudo -i" (or "su -" on debian in my case), then change to your NetBox folder and activate the venv.

Like @cruse1977 said, this is a permission issue which cannot be solved by the plugin. You have probably installed the plugin before with another user (or superuser). You can check the current owner and rights using "ls -la /opt/netbox/netbox/static/netbox_topology_views".

Converting this into a discussion as it's not a bug but an individual issue.
